### PR TITLE
Added signed projects & nuspec files.

### PR DESCRIPTION
**Pull request by klauzy**
When I need to use the compression library, I found that I can't because the libraries are not signed, and can't be used in signed projects.

For that, I replicated the existing projects & nuspec files, using the same code & signing them.

### CODE REVIEW

**Comment by azzlack** [comment]
Fixes #9

**Comment by azzlack** [comment]
Will release this to nuget later today

**Comment by Roemer** [comment]
Is this available on nuget now?

**Comment by azachert** [comment]
Is the signed version available on nuget?

**Pull request merged**
